import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
// import "./globals.css"; // Commenting out default global styles

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script type="module" src="https://cdn.jsdelivr.net/npm/ldrs/dist/auto/helix.js" strategy="beforeInteractive" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
